
Ttree:
  Cloudflare:
    default:
      zone: 'need-to-be-configured'
      apiKey: 'need-to-be-configured'
      email: 'api@domain.com'
    'domain_com':
      zone: 'domain.com'
      apiKey: 'need-to-be-configured'
      email: 'api@domain.com'