
Ttree:
  Cloudflare:
    zone:
      default:
        zone: 'need-to-be-configured'
        apiKey: 'need-to-be-configured'
        email: 'api@domain.com'
      'domain_com':
        enable: FALSE
        zone: 'domain.com'
        apiKey: 'need-to-be-configured'
        email: 'api@domain.com'